### ISSUE TITLE
GUI can die if I click "Run" too soon after a previous action completed

### ISSUE THREAD

**Issue by sea-bass** [matthias-mayr/skiros2_pyrobosim_lib#9]
If I click the "Run" button on a new skill immediately after another one completes, the SkiROS2 GUI dies.

The error:

```
[rqt_gui-3] Traceback (most recent call last):
[rqt_gui-3]   File "/delib_ws/build/skiros2_gui/skiros2_gui/core/skiros_widget.py", line 1336, in on_skill_exe_button_clicked
[rqt_gui-3]     if self._sli.agent.execute(execution_id=self._sli.agent.task):
[rqt_gui-3]        ^^^^^^^^^^^^^^^
[rqt_gui-3]   File "/delib_ws/build/skiros2_skill/skiros2_skill/ros/skill_layer_interface.py", line 31, in agent
[rqt_gui-3]     return next(iter(self._agents.values()))
[rqt_gui-3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rqt_gui-3] StopIteration
```

**Comment by matthias-mayr** [comment]
Thanks for reporting this. I think I should merge https://github.com/RobotLabLTH/skiros2_std_lib/pull/15 that should cure this one as well and will make everything more responsive. I was a bit hesitant first so shortly before the workshop since it's new, but it should tackle a couple of things
